### ISSUE TITLE
Provide ability to scope articles when building a site

### ISSUE THREAD

**Issue by pacomendes** [SPANDigital/presidium#164]
As an author, I would like the ability to scope articles that should be included when publishing a site. This would allow building sites with private and public content.

Article Frontmatter:
```
---
title: Title
scope: internal | external # Optional
---
```

Example Config:
```
show:
  scope: true | false # whether to show or hide scope

sections:
   - title: “Reference”
      url: “/reference/“
      collection: “/reference/“
      scope: internal | external # Optional applies to all in section
```

Build:
```
$ presidium [build | start] -scope [internal | external]
```
